apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-secret: basic-auth-secret
    nginx.ingress.kubernetes.io/auth-type: basic
  name: alarm
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
  - host: k8s.alarm
    http:
      paths:
      - backend:
          service:
            name: alertmanager-operated
            port: 
              number: 9093
        path: /
        pathType: ImplementationSpecific
  - host: k8s_internal.alarm
    http:
      paths:
      - backend:
          service:
            name: alertmanager-operated
            port:
              number: 9093
        path: /
        pathType: ImplementationSpecific
  tls:
    - hosts:
        - k8s.alarm
        - k8s_internal.alarm
      secretName: monitoring-certs
