# This section includes base Calico installation configuration.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
  namespace: kube-system
spec:
  # Configures Calico networking.
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
      - blockSize: {defaultBlockSize}
        cidr: '{defaultCidr}'
#        encapsulation: VXLANCrossSubnet
#        encapsulation: IPIPCrossSubnet
        encapsulation: '{encapsulation}'
        natOutgoing: Enabled
        nodeSelector: all()


#    nodeAddressAutodetectionV4:
#      interface: eth1

#  variant: Calico
#  imagePullSecrets:
#    - name: tigera-pull-secret
#      registry: myregistry.com

---

# This section configures the Calico API server.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}
